#!/bin/bash

# This script is responsible for getting types generated by TypeScript complier
# and copy them to the common folder in order to share the types with the
# frontend and mobile.

types_output="../../packages/common/src/types"
types_files=$(find ./dist -type f -name '*.dto.d.ts' -o  -name '*.interface.d.ts')
rm -rf "${types_output}"
mkdir -p $_
for p in $types_files; do
    mkdir -p "${types_output}/$(dirname ${p:7})";
    cp ${p} $_/$(basename ${p});
done