// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​e​l​e​c​t​ ​l​a​n​g​u​a​g​e
	 */
	selectLanguage: string
	/**
	 * T​o​g​g​l​e​ ​t​h​e​m​e
	 */
	toggleTheme: string
	/**
	 * S​e​l​e​c​t​ ​t​h​e​m​e
	 */
	selectTheme: string
	/**
	 * L​i​g​h​t
	 */
	light: string
	/**
	 * D​a​r​k
	 */
	dark: string
	/**
	 * S​y​s​t​e​m
	 */
	system: string
}

export type TranslationFunctions = {
	/**
	 * Select language
	 */
	selectLanguage: () => LocalizedString
	/**
	 * Toggle theme
	 */
	toggleTheme: () => LocalizedString
	/**
	 * Select theme
	 */
	selectTheme: () => LocalizedString
	/**
	 * Light
	 */
	light: () => LocalizedString
	/**
	 * Dark
	 */
	dark: () => LocalizedString
	/**
	 * System
	 */
	system: () => LocalizedString
}

export type Formatters = {}
